### ISSUE TITLE
Issue in import GDAL

### ISSUE THREAD

**Issue by satyaprakash724** [PratyushTripathy/Land-Cover-Using-Machine-Learning#1]
Python and gdal have been completely installed.
But when I try to import GDAL in cmd it shows an error. Please help me out with these issues.

![Screenshot (215)](https://user-images.githubusercontent.com/87126581/124910476-40b71580-e009-11eb-91e9-a66f4b5f2851.png)

**Comment by PratyushTripathy** [comment]
This issue is a copy of an old one. Check details [here](https://github.com/PratyushTripathy/python_gdal_automated_windows/tree/main/debugger). Hope this works. If not, create an issue on [this](https://github.com/PratyushTripathy/python_gdal_automated_windows) repo.
